### ISSUE TITLE
NM-220 missing in the ontology

### ISSUE THREAD

**Issue by egonw** [enanomapper/ontologies#120]

**Comment by egonw** [comment]
From a NANoREG document [0]:

![image](https://user-images.githubusercontent.com/26721/31767292-c9bbf67a-b4ca-11e7-95f2-e438da3b595b.png)

Do we need those subtypes too?

0. https://www.nanoreg.eu/images/files/MTC_2015/05.2_20150612_ENF2015_Jensen.pdf

**Comment by vedina** [comment]
No, these are not subtypes, these are NR partners

**Comment by egonw** [comment]
Yes, I understood they are partners... but could be different batches? That's what I should have been asking...

**Comment by vedina** [comment]
No, batches have different identification, not by partner names. This is just saying who did the experiment, it's not NM id.  NM identifiers are all in the DB https://search.data.enanomapper.net/nanoreg. 

P.S. a typical curation issue, need to understand the context in order to find out what some piece of info means ...
