### ISSUE TITLE
Merge 2 items (both Fe3O4)

### ISSUE THREAD

**Issue by fehrhart** [enanomapper/ontologies#39]
http://purl.bioontology.org/ontology/npo#NPO_1548	iron(II,III) oxide 
and
http://purl.obolibrary.org/obo/CHEBI_50823	magnetite	
they are identical (both Fe3O4 nanoparticles)

**Comment by JKChang2015** [comment]
done

**Comment by G-Owen** [comment]
suggest we retain the iron(II,III) oxide nanoparticle (NPO_1548) but ensure that 'magnetite nanoparticle' is retained as a synonym.
Retain the is_a iron oxide nanoparticle (NPO_729) which is_a metal oxide nanoparticle (NPO_1541)  classification, but metal oxide nanoparticle (NPO_1541) should be is_a inorganic nanoparticle, (CHEBI_52855) rather than is_a nanoparticle (NPO_707)
