### ISSUE TITLE
[TERM REQUEST] imogolite

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#409]
**What would you use as label or labels for the terms?**
Imogolite

**What is the definition of the term?**
https://en.wikipedia.org/wiki/Imogolite

**Is there an ontology that has this term?**
https://bioportal.bioontology.org/ontologies/IOBC?p=classes&conceptid=http%3A%2F%2Fpurl.jp%2Fbio%2F4%2Fid%2F200906052985562802 

https://bioportal.bioontology.org/ontologies/SWEET?p=classes&conceptid=http%3A%2F%2Fsweetontology.net%2FmatrMineral%2FImogolite

**Additional context**
HARMLESS use case materials

**Comment by vedina** [comment]
I am sorry, but CHEBI_48730 is aluminosilicate, not imogolite.     Kaolin https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:140503 is an aluminosilicate which is NOT imogolite . We need to distinguish between those.

**Comment by jmillanacosta** [comment]
> I am sorry, but CHEBI_48730 is aluminosilicate, not imogolite. Kaolin https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:140503 is an aluminosilicate which is NOT imogolite . We need to distinguish between those.


@vedina Thank you for pointing this out, the issue is that the term isn't in the release version yet.
c1a9c9389e0da240ba8a253bdca240a5422dd218 added aluminosilicate to the slim config for CHEBI 
30d6bb6c288cdd516553bcc52cdd65b7f842a9c4 added Imogolite as subclass of aluminosilicate

The class for aluminosilicate in the development slim: https://github.com/enanomapper/ontologies/blob/be888320b9f57b9d370c4d6d11022b58ebf2d955/external-dev/chebi-slim.owl#L528-L540
The class for imogolite in the development internal term file: https://github.com/enanomapper/ontologies/blob/be888320b9f57b9d370c4d6d11022b58ebf2d955/internal-dev/chebi-ext.owl#L1053-L1058

I think you can already use these identifiers safely. We need to make smaller releases more frequently to make sure this doesn't happen.

Is the issue ready to be closed?

**Comment by jmillanacosta** [comment]
> I am sorry, but CHEBI_48730 is aluminosilicate, not imogolite. Kaolin https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:140503 is an aluminosilicate which is NOT imogolite . We need to distinguish between those.


@vedina Thank you for pointing this out, the issue is that the term isn't in the release version yet.
c1a9c9389e0da240ba8a253bdca240a5422dd218 added aluminosilicate to the slim config for CHEBI 
30d6bb6c288cdd516553bcc52cdd65b7f842a9c4 added Imogolite as subclass of aluminosilicate

The class for aluminosilicate in the development slim: https://github.com/enanomapper/ontologies/blob/be888320b9f57b9d370c4d6d11022b58ebf2d955/external-dev/chebi-slim.owl#L4286-L4296
The class for imogolite in the development internal term file: https://github.com/enanomapper/ontologies/blob/be888320b9f57b9d370c4d6d11022b58ebf2d955/internal-dev/chebi-ext.owl#L1053-L1058

I think you can already use these identifiers safely. We need to make smaller releases more frequently to make sure this doesn't happen.

Is the issue ready to be closed?

**Comment by vedina** [comment]
ok, thanks for the clarification.
