### ISSUE TITLE
biological process entry in BAO

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#48]
Apologies, not really an ENM ontology issue, rather BAO.

It is confusing to find two entries for biological process in BAO :  `biological process`  [BAO_0000264](http://bioportal.bioontology.org/ontologies/BAO/?p=classes&conceptid=http%3A%2F%2Fwww.bioassayontology.org%2Fbao%23BAO_0000264) and `biological_process` [GO_0008150](http://bioportal.bioontology.org/ontologies/BAO/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0008150).  Does anybody has an insight on this (and which entry is recommended)?

**Comment by lrieswijk** [comment]
Hi Nina,

If you look at the definition of the two terms:

BAO_0000264

Any process specifically pertinent to the functioning of integrated living
units: cells, tissues, organs, and organisms. A process is a collection of
molecular events with a defined beginning and end (from GO).

GO_0008150

Note that, in addition to forming the root of the biological process
ontology, this term is recommended for use for the annotation of gene
products whose biological process is unknown. Note that when this term is
used for annotation, it indicates that no information was available about
the biological process of the gene product annotated as of the date the
annotation was made; the evidence code ND, no data, is used to indicate
this. Any process specifically pertinent to the functioning of integrated
living units: cells, tissues, organs, and organisms. A process is a
collection of molecular events with a defined beginning and end.

I would prefer the first term from BAO (BAO_0000264) since this is the more
useful description of a biological process.I guess the second term is only
used when the annotation of the gene products is unknown. This is not very
general and thus not very useful.

I hope this was helpful for you ;)

Kind regards,
Linda

2016-01-22 14:32 GMT+01:00 Nina Jeliazkova <notifications@github.com>:

**Comment by vedina** [comment]
Thanks, Linda!
