### ISSUE TITLE
Help on material types 

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#72]
Could you help which ontology entries to use for 

`BaSO4`,`CaCO3`,
`cellulose`, `Nanofibrillar cellulose`,
`NiFe2O4` (Nickel ferrite?),
`NiZnFe4O8`,
`ZnFe2O4`,
`bentonite`,
`Synthetic Amorphous Silicon` ,
`Silica` 

(is there difference between the last two?)

**Comment by JKChang2015** [comment]
**BaS04:** http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C28859

**cellulose:** http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C68491

**Nanofibrillar cellulose:** It is a kind of cellulose, currently no such entity in existing ontologies, but ChEBI curators are willing to add this element to CheBI database & ontology. 

**Silicon & Silica:**  Silica is a natural form of silicon that’s been slightly oxidized through exposure to oxygen, which forms silicon dioxide (Si02). Many people use the terms silica and silicon dioxide interchangeably because it is rare to find in its non-oxidized form.  According to Gareth's suggestion, **Synthetic Amorphous Silicon** may not be correct a chemical name, it should be **Synthetic Amorphous Silicon Dioxide** or  **Synthetic Amorphous Silica**.

**Comment by vedina** [comment]
Thanks!

**Comment by G-Owen** [comment]
Now available in the ChEBI ontology:
barium sulfate (CHEBI:133326)        [BaSO4]
calcium carbonate (CHEBI:3311)     [CaCO3]
nickel ferrite (CHEBI:133333)           [NiFe2O4]
zinc ferrite (CHEBI:133337)              [ZnFe2O4]
nickel-zinc ferrite (CHEBI:133340)  [(Ni,Zn)Fe2O4] (equivalent to a mixture of NiFe2O4 + ZnFe2O4 ?)

**Comment by JKChang2015** [comment]
I will add them to eNM ontology shortly.

**Comment by G-Owen** [comment]
Some further ChEBI additions:
cellulose is also known as (1→4)-β-D-glucan (CHEBI:18246)
nanofibrillar cellulose (CHEBI:133349)
bentonite (CHEBI:133354)
amorphous silicon (CHEBI:133352)  [NOT the same as amorphous silica (which has different uses)!]
silicon dioxide (CHEBI:30563) is another name for silica.  [Child terms include:
silicon dioxide nanoparticle (CHEBI:50828), vitreous silica (CHEBI:46729), hydrated silica (CHEBI:64393), diatomaceous earth (CHEBI:82661), chalcedony (CHEBI:46728) and quartz (CHEBI:46727).]
All new entries will be included in the next release of the ChEBI ontology files (1st October).

**Comment by vedina** [comment]
@JKChang2015  is "[NPO_1373": "silica nanoparticle"](http://aber-owl.net/#!silica%20nanoparticle) a correct term? Shouldn't it be `silicon dioxide nanoparticle` instead?

**Comment by JKChang2015** [comment]
all the entries have been added.
